elasticsearch:
  image: elasticsearch
  ports:
    - '9200:9200'
    - '9300:9300'
  volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data/
    - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins/
  ##command: elasticsearch -Des.config=/data/elasticsearch.yml
kibana:
  image: kibana
  links:
    - elasticsearch:elasticsearch
  ports:
    - '5601:5601'
logstash:
  image: smo921/logstash
  environment:
    ES_CONTAINER: elasticsearch
  links:
    - elasticsearch:es
    - redis:redis
  volumes:
    - ./logstash:/logstash.conf.d
redis:
  image: redis
  ports:
    - '6379:6379'
